### ISSUE TITLE
CentsOS-7.9 latest

### ISSUE THREAD

**Issue by jml06** [tttapa/toolchains#2]
Hello
try to install x-tools-x86_64-centos7-linux-gnu-gcc13.tar.xz
untar it and the try:
cmake -B build -S . --toolchain ~/opt/x-tools/x86_64-bionic-linux-gnu.toolchain.cmake
i get 
cmake -B build -S . --toolchain ~/opt/x-tools/x86_64-bionic-linux-gnu.toolchain.cmake
CMake Error: The source directory "/workdir/jml/x-tools" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

What i'm missing ?
Thanks in advance for your help
Best Regards

**Comment by jml06** [comment]
i forgot this information:
uname -a
Linux math10.unice.fr 3.10.0-1062.18.1.el7.vSMP.1.x86_64 #1 SMP Wed Mar 17 07:47:16 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tttapa** [comment]
Hi,

You don't need to run CMake to install the toolchain, just extracting it is enough.  

The `cmake -B build -S . --toolchain ...` command tries to configure the CMake project specified by the `-S` flag, in this case, your current working directory, denoted by `.` (which does not appear to be a CMake project). See [man cmake(1)](https://cmake.org/cmake/help/latest/manual/cmake.1.html) for details.

If you want to compile a C/C++/Fortran project using this toolchain, and if that project uses CMake as its build system generator, then you can use the CMake command from the readme (from inside of the directory of that project).

There's a bit more information in the readme of this other repository: https://github.com/tttapa/docker-arm-cross-toolchain?tab=readme-ov-file#usage (although some of it may be Raspberry Pi-specific).

**Comment by jml06** [comment]
Thank you very much for your quick answer and explanation.
Best
